# Generated by Django 4.2.4 on 2023-08-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesarticle',
            options={'verbose_name': 'Доски', 'verbose_name_plural': 'Тред для игр'},
        ),
    ]
