# Generated by Django 4.2.4 on 2023-08-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Тред', 'verbose_name_plural': 'Доски'},
        ),
    ]
