# Generated by Django 4.2.4 on 2023-08-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Доски', 'verbose_name_plural': 'Тред для новостей'},
        ),
    ]
